// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-NrdXPDGYClaM18Ja8j5DvuQ1YD6LGqg',
    appId: '1:704616577712:web:3c6a13cd1de0d3d608d975',
    messagingSenderId: '704616577712',
    projectId: 'blue-titan',
    authDomain: 'blue-titan.firebaseapp.com',
    storageBucket: 'blue-titan.firebasestorage.app',
    measurementId: 'G-FHZK1RBN1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA56v_AH_-K8mAVE6tRH_LGeDrnsVQ3eD0',
    appId: '1:704616577712:android:4c26df9a5f820e0808d975',
    messagingSenderId: '704616577712',
    projectId: 'blue-titan',
    storageBucket: 'blue-titan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8tOQxODfi1N8Tmn-jbY6MP7XbeFn31QA',
    appId: '1:704616577712:ios:eddc86d65ea7ab5908d975',
    messagingSenderId: '704616577712',
    projectId: 'blue-titan',
    storageBucket: 'blue-titan.firebasestorage.app',
    iosBundleId: 'com.example.bluetitan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8tOQxODfi1N8Tmn-jbY6MP7XbeFn31QA',
    appId: '1:704616577712:ios:eddc86d65ea7ab5908d975',
    messagingSenderId: '704616577712',
    projectId: 'blue-titan',
    storageBucket: 'blue-titan.firebasestorage.app',
    iosBundleId: 'com.example.bluetitan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-NrdXPDGYClaM18Ja8j5DvuQ1YD6LGqg',
    appId: '1:704616577712:web:ba70d431688fa70d08d975',
    messagingSenderId: '704616577712',
    projectId: 'blue-titan',
    authDomain: 'blue-titan.firebaseapp.com',
    storageBucket: 'blue-titan.firebasestorage.app',
    measurementId: 'G-1BLZFFVJ92',
  );
}
